name: Build scratch container and deploy into Cloud
on:
  workflow_dispatch:

env:
  JDK_VERSION: '17'
  GRAALVM_DISTRIBUTION: 'graalvm'
  AWS_REGION: 'us-east-2'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    name: Build fully static native image executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GraalVM Setup
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: ${{env.GRAALVM_DISTRIBUTION}}
          java-version: ${{env.JDK_VERSION}}
          native-image-musl: 'true'
          components: 'native-image'
          native-image-job-reports: 'true'

      - name: Validate GraalVM version and pre-requisites installation
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          echo "gcc version:"; gcc --version

      - name: Generate native image executable Linux
        run: |
          cd ./Serie2-DevelopingCloudJavaApp/spring-aot
          chmod +x mvnw mvnw.cmd
          ./mvnw clean -Pnative native:compile

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: spring-aot-ni
          path: ./Serie2-DevelopingCloudJavaApp/spring-aot/target/spring-aot-ni*

  delivery:
    name: ${{ matrix.cloud }} - Pushing as container into Container registry
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        cloud: [ AWS, Azure ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binary
        id: download
        uses: actions/download-artifact@v3
        with:
          name: spring-aot-ni
          path: ./Serie2-DevelopingCloudJavaApp/spring-aot

      - name: Configure aws credentials
        if: ${{ matrix.cloud }} == 'AWS'}}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Configuring Buildx to build multi-architecture images (arm64,amd64,x86-64,etc)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to AWS ECR
        if: ${{ matrix.cloud }} == 'AWS'}}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Log in to Azure container registry
        if: ${{ matrix.cloud }} == 'Azure'}}
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build, tag, and push docker image to Amazon ECR
        if: ${{ matrix.cloud }} == 'AWS'}}
        uses: docker/build-push-action@v4
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: spring-aot-app
          IMAGE_TAG: 'scratch'
        with:
          context: .
          push: true
          tags: $REGISTRY/$REPOSITORY:$IMAGE_TAG
          file: ${{steps.download.outputs.download-path}}/Dockerfile.scratch
          build-args: APP_FILE=${{steps.download.outputs.download-path}}/spring-aot-ni

      - name: Build, tag, and push docker image to Azure CR
        if: ${{ matrix.cloud }} == 'Azure'}}
        uses: docker/build-push-action@v4
        env:
          REPOSITORY: spring-aot-app
          IMAGE_TAG: 'scratch'
        with:
          context: .
          push: true
          tags: ${{ vars.ACR_NAME }}.azurecr.io/$REPOSITORY:$IMAGE_TAG
          file: ${{steps.download.outputs.download-path}}/Dockerfile.scratch
          build-args: APP_FILE=${{steps.download.outputs.download-path}}/spring-aot-ni


